[package]
name = "wrwr-serde-derive"
description = ""
version = "0.1.0"
authors = ["rigma <rigbuntu@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[lib]
name = "wrwr_serde_derive"
proc-macro = true

[dependencies]
syn = "1.0.21"
quote = "1.0.5"
