[package]
name = "rtp"
version = "0.1.3"
authors = ["rigma <rigbuntu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
