[package]
name = "rtp"
version = "0.1.5"
authors = ["rigma <rigbuntu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
rand = "0.7.3"
