[package]
name = "wrwr-serde"
description = ""
version = "0.1.1"
authors = ["rigma <rigbuntu@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[lib]
name = "wrwr_serde"

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
thiserror = "1.0.16"
